version: '3'

services:
  # Databases
  # ===========================================================================

  # MySQL
  # ---------------------------------------------------------------------------
  db_mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: coderhouse
      MYSQL_DATABASE: coderhouse
      MYSQL_USER: coderhouse
      MYSQL_PASSWORD: coderhouse
    ports:
      - "3308:3306"
    volumes:
      - ./mysql/config/custom.cnf:/etc/mysql/conf.d/custom.cnf

  # PostgreSQL
  # ---------------------------------------------------------------------------
  db_postgres:
    image: postgres
    environment:
      POSTGRES_DB: coderhouse
      POSTGRES_USER: coderhouse
      POSTGRES_PASSWORD: coderhouse
    ports:
      - "5438:5432"

  # Microsoft SQL Server
  # ---------------------------------------------------------------------------
  db_mssql:
    image: mcr.microsoft.com/mssql/server
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: C0d3rhous3
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P C0d3rhous3 -Q 'SELECT 1' || exit 1" ]
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 3s
    ports:
      - "1438:1433"
