# Generated by Django 4.2.8 on 2023-12-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentMSSQL',
            fields=[
                ('agentid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Agent MSSQL',
                'verbose_name_plural': 'Agent MSSQL',
                'db_table': 'agents',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AgentMySQL',
            fields=[
                ('agentid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Agent MySQL',
                'verbose_name_plural': 'Agent MySQL',
                'db_table': 'agents',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AgentPostgres',
            fields=[
                ('agentid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Agent Postgres',
                'verbose_name_plural': 'Agent Postgres',
                'db_table': 'agents',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CallMSSQL',
            fields=[
                ('callid', models.IntegerField(primary_key=True, serialize=False)),
                ('agentid', models.IntegerField(blank=True, null=True)),
                ('customerid', models.IntegerField(blank=True, null=True)),
                ('pickedup', models.SmallIntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('productsold', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Call MSSQL',
                'verbose_name_plural': 'Call MSSQL',
                'db_table': 'calls',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CallMySQL',
            fields=[
                ('callid', models.IntegerField(primary_key=True, serialize=False)),
                ('agentid', models.IntegerField(blank=True, null=True)),
                ('customerid', models.IntegerField(blank=True, null=True)),
                ('pickedup', models.SmallIntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('productsold', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Call MySQL',
                'verbose_name_plural': 'Call MySQL',
                'db_table': 'calls',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CallPostgres',
            fields=[
                ('callid', models.IntegerField(primary_key=True, serialize=False)),
                ('agentid', models.IntegerField(blank=True, null=True)),
                ('customerid', models.IntegerField(blank=True, null=True)),
                ('pickedup', models.SmallIntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('productsold', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Call Postgres',
                'verbose_name_plural': 'Call Postgres',
                'db_table': 'calls',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerMSSQL',
            fields=[
                ('customerid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('occupation', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Customer MSSQL',
                'verbose_name_plural': 'Customer MSSQL',
                'db_table': 'customers',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerMySQL',
            fields=[
                ('customerid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('occupation', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Customer MySQL',
                'verbose_name_plural': 'Customer MySQL',
                'db_table': 'customers',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerPostgres',
            fields=[
                ('customerid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('occupation', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Customer Postgres',
                'verbose_name_plural': 'Customer Postgres',
                'db_table': 'customers',
                'abstract': False,
                'managed': False,
            },
        ),
    ]
