services:
  db_mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: coderhouse
      MYSQL_DATABASE: coderhouse
      MYSQL_USER: coderhouse
      MYSQL_PASSWORD: coderhouse
    ports:
      - "3308:3306"
    volumes:
      - ./csv:/opt/csv
      - ./initdb_mysql:/docker-entrypoint-initdb.d
      - ./config_mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8500:80"
    environment:
      PMA_HOST: db_mysql
      MYSQL_ROOT_PASSWORD: coderhouse

  db_postgres:
    image: postgres
    environment:
      POSTGRES_DB: coderhouse
      POSTGRES_USER: coderhouse
      POSTGRES_PASSWORD: coderhouse
    ports:
      - "5438:5432"
    volumes:
      - ./csv:/opt/csv
      - ./initdb_postgres:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@coderhouse.com
      PGADMIN_DEFAULT_PASSWORD: coderhouse
    ports:
      - "8600:80"
    depends_on:
      - db_postgres

  phppgadmin:
    image: dockage/phppgadmin
    environment:
      PHP_PG_ADMIN_SERVER_HOST: db_postgres
    ports:
      - "8900:80"
    depends_on:
      - db_postgres

#  mssql:
##    image: horizoncrafts/mssql-with-initdb
#    image: mcr.microsoft.com/mssql/server
#    ports:
#      - "1433:1433"
#    volumes:
#      - ./initdb_mssql:/docker-entrypoint-initdb.d
#    environment:
#          ACCEPT_EULA: Y
#          SA_PASSWORD: c0d3RHouse!@
#          MSSQL_PID: "Express"
# docker run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=pain91447485" -e "MSSQL_PID=Evaluation" -p 1443:1433  --name sqlpreview --hostname sqlpreview mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04

  python_with_psycopg2:
    build:
      context: python_with_psycopg2
    depends_on:
      - db_mysql
      - db_postgres
    volumes:
      - ./sql:/opt/sql

  flask_with_postgres:
    build:
      context: flask_with_postgres
    depends_on:
      - db_postgres
    ports:
      - "8700:5000"

  fastapi_with_mysql:
    build:
      context: fastapi_with_mysql
    depends_on:
      - db_mysql
    ports:
      - "8800:8000"
